services:
  app:
    build: .
    command: yarn dev
    ports:
      - '8083:8083'
    volumes:
      - .:/app
      - /app/node_modules

  builder:
    profiles: ['build']
    build: .
    command: yarn build
    volumes:
      - .:/app
      - /app/node_modules
